print("What day of week is now? :")
day_of_week = input()
print("Breakfast calories :")
breakfast = int(input())
print("Lunch calories :")
lunch = int(input())
print("Dinner calories :")
dinner = int(input())
print("Snack calorites :")
snacks = int(input())
sum = breakfast+lunch+dinner+snacks